name:flask_pipeline

on:
  push:
    branches:
      - main

jobs:
  python_app:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v4

      -name: setting up Python in our runner
      uses: actions/setup-python@v5
      with: 
        python-version:'3.12'

      -name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      -name: Setting up test cases
      run: echo "Testing has been completed."
